// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by model-api-gen. DO NOT EDIT.

package generalservice

import (
	time "time"

	"yunion.io/x/onecloud/pkg/apis"
)

type SGeneralService struct {
	apis.SEnabledStatusStandaloneResourceBase

	Code string `json:"code"`

	PrimaryKey string `json:"primary_key"`

	ServiceConfig string `json:"service_config"`

	DataSchema string `json:"data_schema"`

	DataCaptions string `json:"data_captions"`

	OperationSchema string `json:"operation_schema"`
}

type SGeneralServiceProvider struct {
	apis.SEnabledStatusStandaloneResourceBase

	ServiceId string `json:"service_id"`

	ApiEndpoint string `json:"api_endpoint"`

	ConsoleEndpoint string `json:"console_endpoint"`

	ProviderConfig string `json:"provider_config"`

	LastDeepSyncAt time.Time `json:"last_deep_sync_at"`
}
